name = "suze modpack"
author = "gwendalos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b1107eff49d0abde5fc139d8d23c81ef99f8e7fd647eb7533087301cfab907e"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
