name = "suze modpack"
author = "gwendalos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b68bd538656b41474d09d718fee3e0d0a06b69b696d8cfc8be606bad3dbd98f"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
