name = "suze modpack"
author = "gwendalos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2a084a2bdb1ab7ddd0a61e79db377067dd887c70c572f6e37f3ada4eb762d95"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
